export const Stats = {
    consumedItems: {} as Record<string, number>,
    enemiesDefeated: {} as Record<string, number>,
    highestDamage: undefined as number | undefined,
    damageInflicted: undefined as number | undefined,
    highestDefense: undefined as number | undefined,
    highestLuck: undefined as number | undefined,
    attacksDogged: undefined as number | undefined,
    attacksBlocked: undefined as number | undefined,
    fishCaught: undefined as number | undefined,
    herbsForaged: undefined as number | undefined,
    goldFromFarming: undefined as number | undefined,
    healthRestored: undefined as number | undefined,
    healthLost: undefined as number | undefined,
    staminaRestored: undefined as number | undefined,
    staminaLost: undefined as number | undefined,
    nightsSlept: undefined as number | undefined,
    goldSpent: undefined as number | undefined,
    goldEarned: undefined as number | undefined,
};
