import type { InventoryItem } from './types/inventory-item';
import type { Item } from './types/item';

function createInventoryItem(plural?: string, count?: number, equipped?: boolean): InventoryItem {
    return {
        count: count ?? 0,
        equipped: equipped ?? false,
        plural,
    };
}

export const Inventory: Record<Item, InventoryItem> = {
    'Straw Hat': createInventoryItem(),
    'Leather Hat': createInventoryItem(),
    'Iron Helmet': createInventoryItem(),
    'Steel Helmet': createInventoryItem(),
    'Helm of the Ancient Warrior': createInventoryItem(),
    'Cloth Pants': createInventoryItem('', 1, true),
    'Leather Pants': createInventoryItem(''),
    'Iron Legs': createInventoryItem(''),
    'Steel Plate Legs': createInventoryItem(''),
    'Legs of the Ancient Warrior': createInventoryItem(),
    'Cloth Shirt': createInventoryItem(undefined, 1, true),
    'Leather Tunic': createInventoryItem(),
    'Iron Breastplate': createInventoryItem(),
    'Steel Breastplate': createInventoryItem(),
    'Breastplate of the Ancient Warrior': createInventoryItem(),
    'Large Stick': createInventoryItem(),
    'Copper Sword': createInventoryItem(),
    'Iron Sword': createInventoryItem(),
    'Steel Sword': createInventoryItem(),
    'Sword of the Ancient Warrior': createInventoryItem(),
    Rock: createInventoryItem(),
    Spear: createInventoryItem(),
    Arrow: createInventoryItem(),
    'Wooden Bow': createInventoryItem(),
    'Long Bow': createInventoryItem(),
    'Bow of the Ancient Warrior': createInventoryItem(''),
    'Loot (4-7g)': createInventoryItem(''),
    'Loot (21-43g)': createInventoryItem(''),
    'Loot (201-404g)': createInventoryItem(''),
    'Gold Coin': createInventoryItem(),
    Bandage: createInventoryItem(),
    Splint: createInventoryItem(),
    'Herbal Medicine': createInventoryItem(''),
    'Antibacterial Paste': createInventoryItem(''),
    'Pickled Vegetables Jar': createInventoryItem(),
    'Dried Fruit Mix': createInventoryItem('es'),
    'Honeyed Biscuit': createInventoryItem(),
    'Dried Meat Jerky': createInventoryItem(''),
    'Fried Fish': createInventoryItem(''),
    'Small Meat Pie': createInventoryItem(),
    'Smoked Sausage': createInventoryItem(),
    'Trail Cheese & Meat Pack': createInventoryItem(''),
    'Proof of Enemy Kill (Weak)': createInventoryItem(''),
    'Proof of Enemy Kill (Strong)': createInventoryItem(''),
    'Proof of Enemy Kill (Dangerous)': createInventoryItem(''),
    'Proof of Enemy Kill (Legendary)': createInventoryItem(''),
    'Fishing Pole': createInventoryItem(),
    'Medicinal Herbs': createInventoryItem(''),
    'Raw Fish': createInventoryItem(''),
    'Fishing Tackle': createInventoryItem(''),
    'Mortar and Pestle': createInventoryItem(''),
    Bedroll: createInventoryItem(),
    'Energizing Aura': createInventoryItem(),
    'Luck Aura': createInventoryItem(),
    'Healing Aura': createInventoryItem(),
};
