import { Skills } from './game/skills';
import { Inventory } from './game/inventory';
import { Shops } from './game/rooms/mermaid-city/shops';
import { Player } from './game/player';
import { Quests } from './game/quests';
import { GuardHall } from './game/rooms/mermaid-city/guard-hall';
import { DeepCoralReef } from './game/rooms/open-ocean/deep-coral-reef';
import { resultRoom } from './game/rooms/utility-rooms/result-room';
import { SealedCavern } from './game/rooms/open-ocean/sealed-cavern';
import { DarkWaters } from './game/rooms/open-ocean/dark-waters';
import { Velrix } from './game/npcs/velrix';

export default () => {
    Skills.levelSkill('tailKick', 7);
    Skills.levelSkill('bubbleBlast', 7);
    Skills.levelSkill('sirensCall', 7);
    Skills.levelSkill('starfishThrow', 7);
    // Inventory.add('coralArmsArmor', 1, Player);
    // Inventory.add('leviathanArmsArmor', 1, Player);
    // Inventory.equip('leviathanArmsArmor', Player);
    // Inventory.add('leviathanBreastplateArmor', 1, Player);
    // Inventory.add('coralBreastplateArmor', 1, Player);
    // Inventory.equip('coralBreastplateArmor', Player);
    // Inventory.add('leviathanHelmetArmor', 1, Player);
    // Inventory.add('coralHelmetArmor', 1, Player);
    // Inventory.equip('leviathanHelmetArmor', Player);
    // Inventory.add('ringOfLongevity', 1, Player);
    // Inventory.equip('ringOfLongevity', Player);
    // Inventory.add('healthBreastplateEnchantment', 1, Player);
    // Inventory.equip('healthBreastplateEnchantment', Player);
    // Inventory.add('healthArmsEnchantment', 1, Player);
    // Inventory.equip('healthArmsEnchantment', Player);
    // Inventory.add('healthHelmetEnchantment', 1, Player);
    // Inventory.equip('healthHelmetEnchantment', Player);
    Inventory.add('bloomTonic', 2, Player);
    Inventory.add('ringOfProtection', 1, Player);
    Inventory.add('barnacleCoveredCoin', 20, Player);
    Inventory.add('crackedPearl', 5, Player);
    Inventory.add('coralCharm', 5, Player);
    Inventory.add('inkSeersBrokenLens', 5, Player);
    Inventory.add('glassBottleMessage', 5, Player);
    Shops.visited = true;
    GuardHall.visited = true;
    DeepCoralReef.visited = true;
    DarkWaters.visited = true;
    DarkWaters.state.velrixDiscovered = true;
    Velrix.move(DarkWaters);
    SealedCavern.visited = true;
    SealedCavern.state.cavernSealed = false;
    Quests.progress('mainQuest', 'get-requirement-to-fix-crown', { shouldStartQuest: true });

    return resultRoom(Shops, []);
};
