export const Categories = {
    meleeWeapons: ['Large Stick', 'Copper Sword', 'Iron Sword', 'Steel Sword', 'Sword of the Ancient Warrior'] as const,
    rangeWeapons: ['Rock', 'Spear', 'Wooden Bow', 'Long Bow', 'Bow of the Ancient Warrior'] as const,
    headArmor: ['Straw Hat', 'Leather Hat', 'Iron Helmet', 'Steel Helmet', 'Helm of the Ancient Warrior'] as const,
    chestArmor: ['Cloth Shirt', 'Leather Tunic', 'Iron Breastplate', 'Steel Breastplate', 'Breastplate of the Ancient Warrior'] as const,
    legArmor: ['Cloth Pants', 'Leather Pants', 'Iron Legs', 'Steel Plate Legs', 'Legs of the Ancient Warrior'] as const,
    ammo: ['Rock', 'Spear', 'Arrow'] as const,
    loot: ['Loot (4-7g)', 'Loot (21-43g)', 'Loot (201-404g)'] as const,
    consumables: ['Bandage', 'Splint', 'Herbal Medicine', 'Antibacterial Paste'] as const,
    food: [
        'Pickled Vegetables Jar',
        'Dried Fruit Mix',
        'Honeyed Biscuit',
        'Dried Meat Jerky',
        'Fried Fish',
        'Small Meat Pie',
        'Smoked Sausage',
        'Trail Cheese & Meat Pack',
    ] as const,
    weapons: [
        'Rock',
        'Spear',
        'Wooden Bow',
        'Long Bow',
        'Bow of the Ancient Warrior',
        'Large Stick',
        'Copper Sword',
        'Iron Sword',
        'Steel Sword',
        'Sword of the Ancient Warrior',
    ] as const,
    armor: [
        'Straw Hat',
        'Leather Hat',
        'Iron Helmet',
        'Steel Helmet',
        'Helm of the Ancient Warrior',
        'Cloth Shirt',
        'Leather Tunic',
        'Iron Breastplate',
        'Steel Breastplate',
        'Breastplate of the Ancient Warrior',
        'Cloth Pants',
        'Leather Pants',
        'Iron Legs',
        'Steel Plate Legs',
        'Legs of the Ancient Warrior',
    ] as const,
    legendaryDrops: [
        'Sword of the Ancient Warrior',
        'Bow of the Ancient Warrior',
        'Helm of the Ancient Warrior',
        'Breastplate of the Ancient Warrior',
        'Legs of the Ancient Warrior',
    ] as const,
    tools: ['Fishing Pole', 'Fishing Tackle', 'Mortar and Pestle', 'Bedroll'] as const,
    farmingBonus: ['Straw Hat', 'Cloth Shirt', 'Cloth Pants'] as const,
    auras: ['Luck Aura', 'Healing Aura', 'Energizing Aura'] as const,
};
